### PR TITLE
Added tree editor component

### LINKED ISSUE #13: Add section for emf.cloud tree editor framework

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #13

Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>

### CODE REVIEW

**Review by eneufeld — COMMENTED** [review]
Awesome

**Comment by JonasHelming** [comment]
I dont see this online, yet, shouldn't it be published automatically?

**Comment by eneufeld** [comment]
@JonasHelming I triggered the build manually, now it is deployed
@sdirix can you check why the build is not run automatically?

**Comment by sdirix** [comment]
The build was not set up to scan the repository automatically. It's now configured to check every hour whether new commits are available, so at most it takes ~1 hour to be published. If wanted I could also configure a more frequent check or look into triggering the build whenever the master changes (for example via Github Actions).

**Comment by eneufeld** [comment]
on master change would be ideal. But imho publish after 1h should be sufficient. @JonasHelming your call.

**Comment by JonasHelming** [comment]
sounds fine the way it is, thanks!

**Pull request merged**
