### PR TITLE
Add Jenkinsfile to build and publish website

### PR DESCRIPTION
**Pull request by sdirix**
Also use https-url for submodule so Jenkins can use it without
additional credentials.

### CODE REVIEW

**Review by eneufeld — APPROVED** [review]
Awesome!

**Comment by eneufeld** [comment]
Can we consume this in our emfcloud jenkins?

**Comment by sdirix** [comment]
Already integrated in [Jenkins](https://ci.eclipse.org/emfcloud/job/build-and-deploy-emfcloud-website/) :+1:

**Comment by sdirix** [comment]
I'll rebase-merge this for now. I kicked of the discussion for defining merge strategies for our website repositories.

**Pull request merged**
